name: Manually upload specific release to dev.bukkit.org

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release to upload'
        required: true

jobs:
  manually_upload_dbo_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: release-info
        uses: cardinalby/git-get-release-action@1.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.event.inputs.version }}

      - name: Download release artifact
        id: release-artifact
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ steps.release-info.outputs.tag_name }}
          file: multiverse-core-${{ steps.release-info.outputs.tag_name }}.jar

      - name: Parse release type
        run: |
          if [[ "${{ steps.release-info.outputs.prerelease }}" == "true" ]]; then
              echo "RELEASE_TYPE=beta" >> $GITHUB_ENV
          else
              echo "RELEASE_TYPE=release" >> $GITHUB_ENV
          fi

      - name: Upload to dev.bukkit.org
        uses: benwoo1110/dbo-upload-action@v0.1.0
        with:
          api_token: ${{ secrets.DBO_UPLOAD_API_TOKEN }}
          project_id: 30765
          changelog: ${{ steps.release-info.outputs.body }}
          changelog_type: markdown
          display_name: ${{ steps.release-artifact.outputs.version }}
          game_versions: 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.18.1, 1.18.2, 1.19, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1
          release_type: ${{ env.RELEASE_TYPE }}
          project_relations: >
            [
              {"slug": "multiverse-portals", "type": "optionalDependency"},
              {"slug": "multiverse-netherportals", "type": "optionalDependency"},
              {"slug": "multiverse-signportals", "type": "optionalDependency"},
              {"slug": "multiverse-inventories", "type": "optionalDependency"}
            ]
          file_path: ${{ github.workspace }}/subdir/multiverse-core-${{ steps.release-artifact.outputs.version }}.jar
