name: Manually promote prerelease to release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote'
        required: true

jobs:
  manually_promote_release:
    runs-on: ubuntu-latest
    steps:
      - name: Verify input version is prerelease
        run: |
          if [[ "${{ github.event.inputs.version }}" != *"pre"* ]]; then
              echo "Version must be a prerelease"
              exit 1
          fi

      - name: Get release info
        id: get-release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event.inputs.version }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-release.outputs.tag_name }}

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x assemble -x shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: release
        uses: benwoo1110/semantic-release-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_mode: promote
          promote_from: ${{ github.event.inputs.version }}

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_VERSION: ${{ steps.release.outputs.publish_version }}

      - name: Upload release artifact
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/multiverse-core-${{ steps.release.outputs.publish_version }}.jar
          asset_name: multiverse-core-${{ steps.release.outputs.tag_name }}.jar
          tag: ${{ steps.release.outputs.tag_name }}

      - name: Download release artifact
        id: release-artifact
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ steps.release.outputs.tag_name }}
          file: multiverse-core-${{ steps.release.outputs.tag_name }}.jar

      - name: Upload to modrinth.com
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build modrinth
        env:
          GITHUB_VERSION: ${{ env.VERSION }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.release.outputs.body }}
          VERSION_NUMBER: ${{ steps.release.outputs.tag_name }}
          VERSION_TYPE: ${{ env.RELEASE_TYPE }}

      - name: Upload to dev.bukkit.org
        uses: benwoo1110/dbo-upload-action@v0.2.0
        with:
          api_token: ${{ secrets.DBO_UPLOAD_API_TOKEN }}
          project_id: 30765
          changelog: ${{ steps.release.outputs.body }}
          changelog_type: markdown
          display_name: ${{ steps.release.outputs.tag_name }}
          game_versions: 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.18.1, 1.18.2, 1.19, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1
          release_type: ${{ env.RELEASE_TYPE }}
          project_relations: >
            [
              {"slug": "multiverse-portals", "type": "optionalDependency"},
              {"slug": "multiverse-netherportals", "type": "optionalDependency"},
              {"slug": "multiverse-signportals", "type": "optionalDependency"},
              {"slug": "multiverse-inventories", "type": "optionalDependency"}
            ]
          file_path: ${{ github.workspace }}/subdir/multiverse-core-${{ steps.release.outputs.tag_name }}.jar
