name: Create Release Version & Publish Package

on:
  push:
    branches: [main]

jobs:
  release_on_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x assemble -x shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: release
        uses: benwoo1110/semantic-release-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_bump: prlabel
          release_mode: prerelease

      - name: Publish package
        if: steps.release.outputs.release_created == 'true'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_VERSION: ${{ steps.release.outputs.publish_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifact
        if: steps.release.outputs.release_created == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/multiverse-core-${{ steps.release.outputs.publish_version }}.jar
          asset_name: multiverse-core-${{ steps.release.outputs.tag_name }}.jar
          tag: ${{ steps.release.outputs.tag_name }}

      - name: Download release artifact
        if: steps.release.outputs.release_created == 'true'
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ steps.release.outputs.tag_name }}
          file: multiverse-core-${{ github.event.inputs.version }}.jar

      - name: Upload to modrinth.com
        if: steps.release.outputs.release_created == 'true'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build modrinth -x checkstyleMain -x checkstyleTest
        env:
          GITHUB_VERSION: ${{ steps.release.outputs.publish_version }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.release.outputs.body }}
          VERSION_NUMBER: ${{ steps.release.outputs.tag_name }}
          VERSION_TYPE: ${{ steps.release.outputs.release_type }}

      - name: Upload to dev.bukkit.org
        if: steps.release.outputs.release_created == 'true'
        uses: benwoo1110/dbo-upload-action@v0.2.0
        with:
          api_token: ${{ secrets.DBO_UPLOAD_API_TOKEN }}
          project_id: 30765
          changelog: ${{ steps.release.outputs.body }}
          changelog_type: markdown
          display_name: ${{ steps.release.outputs.tag_name }}
          game_versions: 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.18.1, 1.18.2, 1.19, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.20, 1.20.1
          release_type: ${{ steps.release.outputs.release_type }}
          project_relations: >
            [
              {"slug": "multiverse-portals", "type": "optionalDependency"},
              {"slug": "multiverse-netherportals", "type": "optionalDependency"},
              {"slug": "multiverse-signportals", "type": "optionalDependency"},
              {"slug": "multiverse-inventories", "type": "optionalDependency"}
            ]
          file_path: ${{ github.workspace }}/multiverse-core-${{ steps.release.outputs.tag_name }}.jar
